<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="5" total="18" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35760" started-at="2021-09-18T15:09:47Z" finished-at="2021-09-18T15:10:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="19173" started-at="2021-09-18T15:09:47Z" finished-at="2021-09-18T15:10:06Z">
      <class name="com.susheel.tests.Seleniumdemo">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="openBrowser" is-config="true" duration-ms="4354" started-at="2021-09-18T11:09:47Z" finished-at="2021-09-18T11:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="validateTitle()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="validateTitle" duration-ms="28" started-at="2021-09-18T11:09:51Z" finished-at="2021-09-18T11:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="FAIL" signature="login()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="login" duration-ms="7584" started-at="2021-09-18T11:09:51Z" finished-at="2021-09-18T11:09:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome Tom] but found [Welcome 2323@@@@11]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome Tom] but found [Welcome 2323@@@@11]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.susheel.tests.Seleniumdemo.login(Seleniumdemo.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="myDetails()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="myDetails" duration-ms="1363" started-at="2021-09-18T11:09:59Z" finished-at="2021-09-18T11:10:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myDetails -->
        <test-method status="PASS" signature="dateSelect()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="dateSelect" duration-ms="3572" started-at="2021-09-18T11:10:00Z" finished-at="2021-09-18T11:10:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dateSelect -->
        <test-method status="PASS" signature="gender()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="gender" duration-ms="73" started-at="2021-09-18T11:10:04Z" finished-at="2021-09-18T11:10:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gender -->
        <test-method status="PASS" signature="nationality()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="nationality" duration-ms="1255" started-at="2021-09-18T11:10:04Z" finished-at="2021-09-18T11:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nationality -->
        <test-method status="FAIL" signature="firstNameTest()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="firstNameTest" duration-ms="46" started-at="2021-09-18T11:10:05Z" finished-at="2021-09-18T11:10:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Tom] but found [tom]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Tom] but found [tom]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.susheel.tests.Seleniumdemo.firstNameTest(Seleniumdemo.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameTest -->
        <test-method status="PASS" signature="lastNameTest()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="lastNameTest" duration-ms="34" started-at="2021-09-18T11:10:05Z" finished-at="2021-09-18T11:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameTest -->
        <test-method status="PASS" signature="dateTest()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="dateTest" duration-ms="23" started-at="2021-09-18T11:10:05Z" depends-on-methods="com.susheel.tests.Seleniumdemo.lastNameTest" finished-at="2021-09-18T11:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dateTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.susheel.tests.Seleniumdemo@60addb54]" name="closeBrowser" is-config="true" duration-ms="789" started-at="2021-09-18T11:10:05Z" finished-at="2021-09-18T11:10:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.susheel.tests.Seleniumdemo -->
    </test> <!-- Test -->
    <test name="Test2" duration-ms="16569" started-at="2021-09-18T15:10:06Z" finished-at="2021-09-18T15:10:22Z">
      <class name="com.susheel.tests.Seleniumdemo2">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="openBrowser" is-config="true" duration-ms="2409" started-at="2021-09-18T11:10:06Z" finished-at="2021-09-18T11:10:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="validateTitle()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="validateTitle" duration-ms="19" started-at="2021-09-18T11:10:08Z" finished-at="2021-09-18T11:10:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="FAIL" signature="login()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="login" duration-ms="7269" started-at="2021-09-18T11:10:08Z" finished-at="2021-09-18T11:10:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome Tom] but found [Welcome tom]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome Tom] but found [Welcome tom]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.susheel.tests.Seleniumdemo2.login(Seleniumdemo2.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="myDetails()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="myDetails" duration-ms="1025" started-at="2021-09-18T11:10:16Z" finished-at="2021-09-18T11:10:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myDetails -->
        <test-method status="PASS" signature="dateSelect()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="dateSelect" duration-ms="3507" started-at="2021-09-18T11:10:17Z" finished-at="2021-09-18T11:10:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dateSelect -->
        <test-method status="PASS" signature="gender()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="gender" duration-ms="66" started-at="2021-09-18T11:10:20Z" finished-at="2021-09-18T11:10:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gender -->
        <test-method status="PASS" signature="nationality()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="nationality" duration-ms="1367" started-at="2021-09-18T11:10:20Z" finished-at="2021-09-18T11:10:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nationality -->
        <test-method status="FAIL" signature="firstNameTest()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="firstNameTest" duration-ms="38" started-at="2021-09-18T11:10:22Z" finished-at="2021-09-18T11:10:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Tom] but found [tom]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Tom] but found [tom]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.susheel.tests.Seleniumdemo2.firstNameTest(Seleniumdemo2.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstNameTest -->
        <test-method status="FAIL" signature="lastNameTest()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="lastNameTest" duration-ms="30" started-at="2021-09-18T11:10:22Z" finished-at="2021-09-18T11:10:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1234] but found [admin123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1234] but found [admin123]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.susheel.tests.Seleniumdemo2.lastNameTest(Seleniumdemo2.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastNameTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="closeBrowser" is-config="true" duration-ms="834" started-at="2021-09-18T11:10:22Z" finished-at="2021-09-18T11:10:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="SKIP" signature="dateTest()[pri:0, instance:com.susheel.tests.Seleniumdemo2@13c78c0b]" name="dateTest" duration-ms="0" started-at="2021-09-18T11:10:22Z" depends-on-methods="com.susheel.tests.Seleniumdemo2.lastNameTest" finished-at="2021-09-18T11:10:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dateTest -->
      </class> <!-- com.susheel.tests.Seleniumdemo2 -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
